version: '3.5'

services:
  postgresql:
    restart: always
    image: postgres:10.3
    environment:
      POSTGRES_PASSWORD: 1234qwer
    volumes:
      - ../data/blockscout/ssl/server.crt:/var/lib/postgresql/ssl/server.crt
      - ../data/blockscout/ssl/server.key:/var/lib/postgresql/ssl/server.key
      - ../data/blockscout-db:/var/lib/postgresql/data
    command:
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/ssl/server.crt
      -c ssl_key_file=/var/lib/postgresql/ssl/server.key
